[package]
name = "maturin-nix"
version = "0.1.0"
authors = ["Christopher Chalmers <c.chalmers@me.com>"]
edition = "2018"

exclude = [
  "examples/*",
]

[dependencies]
maturin = { path = "../pyo3-pack" }
structopt = "0.3"
ansi_term = "0.12"
